---
- name: Enable shadowsocks COPR repository
  get_url:
    dest: /etc/yum.repos.d/_copr_librehat-shadowsocks.repo
    url: "https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/repo/{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'epel') }}-{{ ansible_distribution_major_version }}/librehat-shadowsocks-{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'epel') }}-{{ ansible_distribution_major_version }}.repo"

- name: Enable EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution != "Fedora"

- name: Install shadowsocks
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - shadowsocks-libev
